/**
 * Source pane: the LaTeX source of the document (what its .tex file contains), generated by the
 * server from the live editor state, shown in a panel below the writing area with syntax colours
 * (texhighlight.ts: a coloured copy of the text lies under a transparent textarea). It follows the
 * cursor — the paragraph being edited is scrolled into view and its first line marked — and it is
 * editable: "Apply" sends the edited source back; the server parses it and replaces the document
 * content through the normal collaborative channel (as a diff, so paragraphs that did not change
 * keep their identity). Undo / redo in the pane is our own (codearea.ts, the browser's breaks
 * when the text is regenerated), and the bracket pair at the cursor is marked in the colours.
 */
import { useEffect, useMemo, useRef, useState } from 'preact/hooks';
import type { EditorView } from 'prosemirror-view';
import type * as Y from 'yjs';
import { writeLyx, pmToLyxBody } from '@overlyx/core';
import { api } from '../api';
import { highlightTex, highlightLines } from './texhighlight';
import { UndoStack, undoRedoKey, applyUndoRedo, applySnapshot, editingKey, matchBrackets, commentMask } from './codearea';
import { findSourceLine } from './sourcelocate';
import type { LyxMathField } from '../editor/lyxmath/field';

export interface SourceTarget { view: EditorView; ydoc: Y.Doc; docId: string }

/** line height of the source text (px; styles.css `.source-pane .code`) */
const LINE_H = 15;
const PAD_TOP = 6;
const MIN_H = 100;
const DEFAULT_H = 240;

function metaOf(ydoc: Y.Doc) {
  const m = ydoc.getMap<string>('meta');
  const parse = (k: string, def: unknown) => { try { const v = m.get(k); return v ? JSON.parse(v) : def; } catch { return def; } };
  return {
    preamble: parse('preamble', []) as string[],
    format: parse('format', 643) as number,
    header: parse('header', []) as string[],
    trailer: parse('trailer', []) as string[],
  };
}

/**
 * The document in LyX's file format, generated in the browser (no server needed): the fallback
 * for keeping unsynced offline edits when the server cannot store them — the file can be imported
 * into a project again.
 */
export function generateLyx(t: SourceTarget): string {
  const meta = metaOf(t.ydoc);
  return writeLyx({ preamble: ['#LyX 2.5 created this file. For more info see https://www.lyx.org/'], format: meta.format, header: { lines: meta.header }, body: pmToLyxBody(t.view.state.doc), trailer: meta.trailer });
}

/** the source line of the cursor (see sourcelocate.ts): the text around it, or the formula's row when in math */
export function cursorLine(view: EditorView, text: string, field: LyxMathField | null, prev: number | null): { line: number; offset: number } | null {
  const $from = view.state.selection.$from;
  const par = $from.parent;
  if (!par.isTextblock) return null;
  const atom = String.fromCharCode(0);
  const before = par.textBetween(0, $from.parentOffset, undefined, atom);
  const after = par.textBetween($from.parentOffset, par.content.size, undefined, atom);
  const first = par.firstChild;
  const parStart = first?.isText ? first.text!.slice(0, 48) : undefined;
  let formula: { latex: string; row: number; display: boolean } | undefined;
  if (field?.hasFocus()) formula = { latex: field.latex.replace(/^\$|\$$/g, ''), row: field.topRow(), display: field.display };
  return findSourceLine(text, { before, after, parStart, formula, prev });
}

function storedHeight(): number {
  try { const v = Number(localStorage.getItem('ol.source.h')); return v >= MIN_H ? v : DEFAULT_H; } catch { return DEFAULT_H; }
}

export function SourcePane({ target, tick, selTick, mathField, onNotify, onClose }: { target: SourceTarget | null; tick: number; selTick?: number; /** the formula being edited, if any */ mathField?: LyxMathField | null; onNotify: (msg: string, kind?: 'info' | 'error') => void; onClose?: () => void }) {
  const [text, setText] = useState('');
  const [dirty, setDirty] = useState(false);
  const [busy, setBusy] = useState(false);
  const [curLine, setCurLine] = useState<number | null>(null);
  const lastOffset = useRef<number | null>(null);
  const [height, setHeight] = useState(storedHeight);
  const ta = useRef<HTMLTextAreaElement>(null);
  const pre = useRef<HTMLPreElement>(null);
  const timer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const seq = useRef(0);
  const undo = useRef(new UndoStack({ value: '', start: 0, end: 0 }));
  const [cursor, setCursor] = useState<number | null>(null);
  const mask = useMemo(() => commentMask(text), [text]);
  const match = useMemo(() => (cursor === null ? null : matchBrackets(text, cursor, mask)), [text, cursor, mask]);
  const html = useMemo(() => {
    let marks: Map<number, string> | undefined;
    if (match) {
      marks = new Map();
      const cls = match.kind === 'adjacent' ? 'hl-match' : 'hl-enclose';
      for (const at of [match.open, match.close]) for (let k = 0; k < match.len; k++) marks.set(at + k, cls);
    }
    return highlightLines(highlightTex(text, marks), dirty ? null : curLine);
  }, [text, match, curLine, dirty]);
  const updateCursor = () => { const el = ta.current; if (el) setCursor(el.selectionStart === el.selectionEnd ? el.selectionStart : null); };
  useEffect(() => {
    const h = () => { if (document.activeElement === ta.current) updateCursor(); };
    document.addEventListener('selectionchange', h);
    return () => document.removeEventListener('selectionchange', h);
  }, []);

  const load = async () => {
    if (!target) return;
    const my = ++seq.current;
    try {
      const t = await api.texText(target.docId);
      if (my === seq.current) { setText(t); undo.current.reset({ value: t, start: 0, end: 0 }); }
    } catch (e) { if (my === seq.current) setText('% could not generate source: ' + (e as Error).message); }
  };

  // regenerate the source when the document changes (unless the user is editing the source)
  useEffect(() => {
    if (!target || dirty) return;
    if (timer.current) clearTimeout(timer.current);
    timer.current = setTimeout(() => { void load(); }, 700);
    return () => { if (timer.current) clearTimeout(timer.current); };
  }, [target?.docId, tick, dirty]);

  // the coloured copy scrolls with the textarea
  const syncScroll = () => { if (pre.current && ta.current) { pre.current.scrollTop = ta.current.scrollTop; pre.current.scrollLeft = ta.current.scrollLeft; } };

  // follow the cursor: mark the paragraph's first line and keep it in view (not while editing the source)
  useEffect(() => {
    if (!target || dirty || !text) return;
    const found = cursorLine(target.view, text, mathField ?? null, lastOffset.current);
    lastOffset.current = found?.offset ?? null;
    setCurLine(found?.line ?? null);
  }, [selTick, text, dirty, mathField]);
  // keep the marked line in view (once it is rendered; lines wrap, so it is measured, not computed)
  useEffect(() => {
    const el = ta.current, cur = pre.current?.querySelector('.l.cur') as HTMLElement | null;
    if (!el || !cur || dirty || document.activeElement === el) return;
    const y = cur.offsetTop, h = cur.offsetHeight || LINE_H;
    if (y < el.scrollTop + h || y + h > el.scrollTop + el.clientHeight - h) { el.scrollTop = Math.max(0, y - el.clientHeight / 3); syncScroll(); }
  }, [curLine, html]);

  useEffect(() => { try { localStorage.setItem('ol.source.h', String(Math.round(height))); } catch { /* ignore */ } }, [height]);
  const startResize = (e: PointerEvent) => {
    e.preventDefault();
    const startY = e.clientY, startH = height;
    const move = (ev: PointerEvent) => setHeight(Math.max(MIN_H, Math.min(window.innerHeight * 0.8, startH + startY - ev.clientY)));
    const up = () => { window.removeEventListener('pointermove', move); window.removeEventListener('pointerup', up); };
    window.addEventListener('pointermove', move);
    window.addEventListener('pointerup', up);
  };

  const apply = async () => {
    if (!target) return;
    setBusy(true);
    try {
      const r = await api.applySource(target.docId, text);
      setDirty(false);
      onNotify(r.warnings.length ? `Source applied (${r.warnings.length} warning${r.warnings.length > 1 ? 's' : ''}: ${r.warnings[0]})` : 'Source applied to the document');
    } catch (e) {
      onNotify('Cannot apply source: ' + (e as Error).message, 'error');
    }
    setBusy(false);
  };
  const revert = () => { setDirty(false); void load(); };

  const name = target?.docId.split('/').pop() ?? '';
  return (
    <div class="source-pane bottom" style={{ height: height + 'px' }}>
      <div class="grip" title="Drag to resize" onPointerDown={startResize} />
      <div class="bar">
        <span class="small-btn active" title="The LaTeX source of the document (its .tex file)">LaTeX</span>
        <span class="name" title={target?.docId}>{name}</span>
        <span style="flex:1" />
        {dirty && <button class="small-btn primary" disabled={busy} onClick={() => void apply()} title="Parse the edited source and replace the document">{busy ? '…' : 'Apply'}</button>}
        {dirty && <button class="small-btn" onClick={revert}>Revert</button>}
        {!dirty && <button class="small-btn" onClick={() => void load()} title="Regenerate from the editor">Refresh</button>}
        <button class="small-btn" onClick={() => { void navigator.clipboard?.writeText(text); }} title="Copy to clipboard">Copy</button>
        {onClose && <button class="small-btn close" onClick={onClose} title="Hide the source pane (Ctrl+Alt+S)">✕</button>}
      </div>
      <div class="code">
        <pre class="hl" ref={pre} aria-hidden="true"><code dangerouslySetInnerHTML={{ __html: html }} /></pre>
        <textarea ref={ta} class="source" spellcheck={false} value={text} onScroll={syncScroll} onClick={updateCursor} onKeyUp={updateCursor}
          onInput={e => { const el = e.target as HTMLTextAreaElement; undo.current.record({ value: el.value, start: el.selectionStart, end: el.selectionEnd }); setText(el.value); setDirty(true); updateCursor(); }}
          onKeyDown={e => {
            if ((e.ctrlKey || e.metaKey) && e.key === 'Enter' && dirty) { e.preventDefault(); void apply(); return; }
            const ur = undoRedoKey(e);
            if (ur) { e.preventDefault(); const s = applyUndoRedo(ta.current!, undo.current, ur); if (s) { setText(s.value); setDirty(true); updateCursor(); } return; }
            if (e.isComposing) return;
            const el = ta.current!;
            const s = editingKey(e, el);
            if (s) { e.preventDefault(); applySnapshot(el, s); undo.current.record({ value: el.value, start: el.selectionStart, end: el.selectionEnd }); setText(el.value); setDirty(true); updateCursor(); }
          }} />
      </div>
      <div class="hint">{dirty ? 'Edited — Apply (Ctrl+Enter) replaces the document with this source.' : 'The LaTeX source of the document as it is saved; it follows the cursor. Edit and apply, or copy.'}</div>
    </div>
  );
}
