// Screenshots of the UI's parts in one browser (desktop): the editor with its toolbars and status bar, a context
// menu, the preferences and document settings dialogs, the dark theme. Usage: shots.mts <webkit|firefox|chromium> <outdir>
import { webkit, firefox, chromium, devices } from '@playwright/test';
import { mkdirSync } from 'node:fs';
import { login, BASE_URL, pickTheme } from '../../e2e/helpers';
const name = process.argv[2] ?? 'webkit'; const OUT = process.argv[3] ?? '/tmp/shots';
mkdirSync(OUT, { recursive: true });
const bt = { webkit, firefox, chromium }[name]!;
const dev = { webkit: devices['Desktop Safari'], firefox: devices['Desktop Firefox'], chromium: devices['Desktop Chrome'] }[name]!;
const browser = await bt.launch();
const ctx = await browser.newContext({ ...dev, baseURL: BASE_URL, viewport: { width: 1400, height: 900 }, deviceScaleFactor: 1 });
const page = await ctx.newPage();
const errors: string[] = [];
page.on('pageerror', e => errors.push('pageerror ' + e.message));
page.on('console', m => { if (m.type() === 'error') errors.push('console ' + m.text()); });
await login(page);
await page.goto('/#/admin/e2e-ipad/main.tex');
await page.waitForFunction(() => document.querySelectorAll('.lyx-editor .lyx-par').length > 3, null, { timeout: 60000 });
await page.waitForTimeout(2000);
await page.screenshot({ path: `${OUT}/editor.png` });
await page.locator('.statusbar').screenshot({ path: `${OUT}/statusbar.png` });
await page.locator('.lyx-editor .lyx-par').nth(1).click({ button: 'right', position: { x: 40, y: 8 } });
await page.waitForTimeout(400);
await page.screenshot({ path: `${OUT}/ctxmenu.png` });
await page.keyboard.press('Escape');
await page.evaluate(() => (window as any).overlyx.openDialog('preferences'));
await page.waitForTimeout(800);
await page.screenshot({ path: `${OUT}/prefs.png` });
await page.keyboard.press('Escape');
await page.evaluate(() => (window as any).overlyx.openDialog('document'));
await page.waitForTimeout(800);
await page.screenshot({ path: `${OUT}/docsettings.png` });
await page.keyboard.press('Escape');
await pickTheme(page, 'Dark');
await page.waitForTimeout(800);
await page.screenshot({ path: `${OUT}/dark.png` });
await pickTheme(page, 'Default');
console.log('errors', JSON.stringify(errors));
await browser.close();
