#!/bin/sh
echo
if [ -e .commit ]
    then
    rm .commit
    for file in *.lyx; do
        git add "${file%.lyx}.tex"
        
    git status
    git commit --amend -C HEAD --no-verify
    echo "Commit amended with produced *.tex"
    done
fi
exit