#!/bin/bash

OVERLYX_DIR=~/overlyx

# # Get the absolute path of repo root
# GIT_DIR=$(git rev-parse --show-toplevel)
# $HOOKS_DIR=$(git rev-parse --git-path hooks)

# # Now you can use $GIT_DIR in your hook script
# echo "Git directory: $GIT_DIR"
# echo "Hooks directory: $HOOKS_DIR"
# echo "Overlyx directory: $OVERLYX_DIR"

# Check if .disable_hooks exists in the Git directory
if [ ! -f "$OVERLYX_DIR/.disable_hooks" ]; then
    # .disable_hooks does not exist, so run the Python script
    python "$OVERLYX_DIR/hooks/post-merge.py"
fi
