#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

# Loop through each .lyx file
for file in *.lyx; do
    # Export .lyx to .tex
    lyx --export-to latex "${file%.lyx}.tex" "$file" 
    
    # Modify the .tex file
    awk '/\\begin{document}/,/\\end{document}/ {if (!/\\begin{document}/ && !/\\end{document}/) print}' "${file%.lyx}.tex" > temp_file.tex
    mv temp_file.tex "${file%.lyx}.tex"
done

touch .commit 

echo "Ran pre-commit hook."

exit