#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

lyx --export-to latex theory.tex theory.lyx

awk '/\\begin{document}/,/\\end{document}/ {if (!/\\begin{document}/ && !/\\end{document}/) print}' theory.tex > temp_file.tex
mv temp_file.tex theory.tex

touch .commit 

echo "Ran pre-commit hook."

exit