#!/usr/bin/env python3
"""Regenerate packages/client/src/app/mathpanels.ts from LyX's lib/ui/stdtoolbars.inc (math panel palettes)."""
import re, sys, os
root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src = open(os.path.join(root, '..', 'lib', 'ui', 'stdtoolbars.inc')).read()
blocks = re.findall(r'\n\tToolbar "([^"]+)" "([^"]+)"\n(.*?)\n\tEnd', src, re.S)
want = ['functions','space','sqrt-square','style','frac-square','font','latex_dots','latex_deco','latex_arrow','latex_bop','latex_brel','latex_greek','latex_misc','latex_varsz','latex_ams_misc','latex_ams_arrows','latex_ams_rel','latex_ams_nrel','latex_ams_ops','latex_delim']
out = []
for name, title, body in blocks:
    if name not in want: continue
    items = []
    for line in body.split('\n'):
        line = line.strip()
        if not line or line.startswith('#'): continue
        m = re.match(r'Item "([^"]*)" "([^"]*)"', line)
        if not m: continue
        label, cmd = m.groups()
        label = re.sub(r'\[\[.*?\]\]', '', label).split('\t')[0]
        m2 = re.match(r'(math-insert|math-size) (.*)', cmd)
        if not m2: continue
        kind, arg = m2.groups()
        items.append((label, kind, arg.replace('\\', '\\\\')))
    out.append((name, title, items))
order = {n: i for i, n in enumerate(want)}
out.sort(key=lambda b: order[b[0]])
ts = ['/** LyX math panels (lib/ui/stdtoolbars.inc), generated by scripts/gen-math-panels.py — do not edit. */',
      'export interface PanelItem { label: string; kind: "insert" | "size"; latex: string }',
      'export interface MathPanel { id: string; title: string; items: PanelItem[] }',
      'export const MATH_PANELS: MathPanel[] = [']
for name, title, items in out:
    ts.append(f"  {{ id: '{name}', title: '{title}', items: [")
    for label, kind, arg in items:
        k = 'size' if kind == 'math-size' else 'insert'
        ts.append(f"    {{ label: '{label.replace(chr(39), chr(92)+chr(39))}', kind: '{k}', latex: '{arg}' }},")
    ts.append('  ] },')
ts.append('];')
open(os.path.join(root, 'packages', 'client', 'src', 'app', 'mathpanels.ts'), 'w').write('\n'.join(ts) + '\n')
print(f'{len(out)} panels, {sum(len(i) for _, _, i in out)} items')
