import { chromium } from '@playwright/test';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
const S = '/root/.claude/jobs/9387b0c1/tmp/inst'; const BASE = 'http://localhost:5174';
mkdirSync(S + '/projects/dbg', { recursive: true });
writeFileSync(S + '/projects/dbg/p.tex', '\\documentclass{article}\n\\begin{document}\n\\section{Intro}\n\nRecurrent networks show rich dynamics. We study the exponent of such networks.\n\nThe last paragraph.\n\\end{document}\n');
const [username, password] = readFileSync(S + '/data/credentials.txt', 'utf8').split('\n').filter(l => l.startsWith('admin\t')).pop().split('\t');
const browser = await chromium.launch(); const ctx = await browser.newContext();
await ctx.addInitScript(() => { localStorage.setItem('ol.tour', 'e2e'); localStorage.setItem('ol.prefs', JSON.stringify({ spellcheck: true, aiRewrite: false, aiCompleteText: true, aiCompleteMath: false, aiCompleteDelay: 200 })); });
const page = await ctx.newPage();
page.on('pageerror', e => console.log('pageerror', e.message));
page.on('console', m => { if (m.type() === 'error' || m.text().startsWith('[dbg]')) console.log('console:', m.text().slice(0, 300)); });
await page.goto(BASE + '/'); await page.locator('[data-password-login], input[placeholder="Username"]').first().waitFor();
if (await page.locator('[data-password-login]').count()) await page.locator('[data-password-login]').click();
await page.getByPlaceholder('Username').fill(username); await page.getByPlaceholder('Password').fill(password); await page.getByRole('button', { name: 'Sign in' }).click(); await page.waitForSelector('.menubar');
await page.request.get(BASE + '/api/projects');
await page.goto(BASE + '/#/dbg/p.tex');
await page.waitForFunction(() => document.querySelectorAll('.lyx-editor .lyx-par').length > 2); await page.waitForTimeout(800);
await page.locator('.lyx-editor .lyx-par').nth(1).click({ position: { x: 12, y: 8 } });
await page.evaluate(() => { const v = window.overlyx.activeView; const doc = v.state.doc; const end = doc.child(0).nodeSize + doc.child(1).nodeSize - 1; v.dispatch(v.state.tr.setSelection(v.state.selection.constructor.create(doc, end))); });
// instrument dispatch
await page.evaluate(() => { const v = window.overlyx.activeView; const orig = v.dispatch.bind(v); v.dispatch = (tr) => { const st = () => { const p = v.state.plugins.find(p => String(p.key).startsWith('ai-complete')); return p.getState(v.state); }; const before = st(); orig(tr); const after = st(); console.log('[dbg] tr docChanged=' + tr.docChanged + ' selSet=' + tr.selectionSet + ' steps=' + JSON.stringify(tr.steps.map(s => s.toJSON())).slice(0, 200) + ' sel=' + tr.selection.from + ' ghostBefore=' + (before.ghost ? before.ghost.pos + ':' + JSON.stringify(before.ghost.text.slice(0, 12)) + ' b=' + JSON.stringify(before.ghost.before.slice(-10)) : 'none') + ' ghostAfter=' + (after.ghost ? after.ghost.pos + ':' + JSON.stringify(after.ghost.text.slice(0, 12)) : 'none') + ' meta=' + JSON.stringify(Object.keys(tr.meta))); }; });
await page.keyboard.type(' The chaos');
await page.waitForSelector('.ai-ghost', { timeout: 8000 });
console.log('--- ghost shown; typing " i"');
await page.keyboard.type(' is gov', { delay: 40 });
await page.waitForTimeout(800);
console.log('ghost count:', await page.locator('.ai-ghost').count(), 'text:', await page.locator('.ai-ghost').textContent().catch(() => '(none)'));
await browser.close();
