import { chromium } from '@playwright/test';
import fs from 'node:fs';
const S = process.env.S;
const creds = fs.readFileSync(S + '/data/credentials.txt', 'utf8').split('\n').filter(l => l.startsWith('admin\t')).pop().split('\t');
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1500, height: 900 }, deviceScaleFactor: 1.5 });
await page.goto('http://localhost:5184/');
await page.getByPlaceholder('Username').fill(creds[0]); await page.getByPlaceholder('Password').fill(creds[1]);
await page.getByRole('button', { name: 'Sign in' }).click(); await page.waitForSelector('.menubar');
await page.evaluate(() => { localStorage.setItem('ol.tabs', '[]'); localStorage.removeItem('ol.toolbars'); });
await page.goto('http://localhost:5184/#/recurrent_feature/main.lyx');
await page.waitForFunction(() => document.querySelectorAll('.lyx-editor .lyx-par').length >= 3);
await page.waitForTimeout(2500);
await page.locator('.lyx-editor .lyx-math-inline').nth(3).click();
await page.waitForSelector('.toolbar-math');
await page.waitForTimeout(300);
await page.screenshot({ path: S + '/shot-toolbars.png', clip: { x: 0, y: 0, width: 1500, height: 190 } });
await page.locator('[data-tb="m-delims"]').click();
await page.waitForTimeout(400);
await page.screenshot({ path: S + '/shot-delims.png', clip: { x: 0, y: 60, width: 1100, height: 760 } });
await page.locator('[data-tb="mp-latex_greek"]').click();
await page.waitForTimeout(400);
await page.screenshot({ path: S + '/shot-greek.png', clip: { x: 0, y: 60, width: 1100, height: 450 } });
await page.locator('[data-tb="mp-latex_deco"]').click();
await page.waitForTimeout(400);
await page.screenshot({ path: S + '/shot-deco.png', clip: { x: 0, y: 60, width: 1200, height: 450 } });
await page.locator('[data-tb="mp-frac-square"]').click();
await page.waitForTimeout(400);
await page.screenshot({ path: S + '/shot-frac.png', clip: { x: 0, y: 60, width: 1200, height: 500 } });
await browser.close();
